home.php

Previously, the link to the get-started page would not lead anywhere, should be fine now.

Add a link to the get-started page

---

public/docs/index.html

For some reason the link was missing on this page.

Add link for emit-cheatsheet on main docs page

---

public/docs/index.html

For express
sendfile deceprated and express gives warning
Has been removed in express 5
https://github.com/expressjs/express/blob/5.0/History.md
5.0.0-alpha.1 / 2014-11-06

Changed res.senfile to res.sendFile

---

public/assets/js/home.js

I know this is really minor, but figured I'd mention it anyway.
Was just on the site and noticed that the site jumps instantly to the features section, and then scrolls down.
I believe just adding the preventDefault function should stop that blink at the beginning.

Stop page jump on arrow click

---

source/_posts/20150714-p2p.md

Fixed the order of values in the config object according to https://github.com/socketio/socket.io-p2p#api and https://github.com/feross/simple-peer/blob/master/README.md#api

Fixed options for p2p server

---

source/docs/logging-and-debugging.md

That backtick shouldn't be there. At least, my code didn't work it.

Removing a backtick from the DEBUG statement

---

source/docs/index.md

Updated the docs to provide a better example of passing arguments to acknowledgement callback functions.

Update example for acknowledgement callbacks

---

themes/socket.io/source/css/home.styl

propbably the same as #76 that solves #73 but without messing with negative margins.
the reason was that the the [edtor title](https://github.com/socketio/socket.io-website/blob/master/themes/socket.io/source/css/home.styl#L133-L139) were overflowing becasuse of its `width`.

 docs: re-fix editor window title position 

---

source/docs/client-api.md

Both `reconnecting` and `reconnect_attempt` are exactly the same thing.
This PR corrects descriptions of that events on top of client api docs page:
https://socket.io/docs/client-api/#Event-%E2%80%98reconnect-attempt%E2%80%99

fix: correct description of reconnecting and reconnect_attempt events

---

source/docs/index.md

[python-socketio](https://python-engineio.readthedocs.io/en/latest/client.html) is a more maintained project.

Updated Python client link

---

source/get-started/chat.md

Currently, the example on GitHub hosted [here](https://github.com/socketio/chat-example/blob/master/index.html) specifies a CDN to host the client-side JS.
```html
<script src="https://cdn.socket.io/socket.io-1.2.0.js"></script>
```
However, it may be good to be explicit that socket.io exposes the API endpoint for them automatically, but they can use a CDN if they choose or use the one in the `dist` folder, given that they make the appropriate change to the script's `src` tag. As a new user to `socket.io`, I didn't realize that `/socket.io/socket.io.js` was automatically exposed.

Add clarification on hosting the client JS file

---

themes/socket.io/source/css/home.styl

Hello 👋
On chrome and firefox the code in the left `window` stretches past the container. Changing the width to 42% seems to fix the issue. 
Here is a screenshot of the issue.
Hope this helps 😄

Change window size to 42%

---

source/_posts/20150120-native-socket-io-and-android.md

The current version of the android library on the documentation is wrong, I updated it with the newest version from the [maven repo](https://mvnrepository.com/artifact/com.github.nkzawa/socket.io-client/0.5.0)

Updated android lib version to the newest

---

source/socket-io-with-apache-cordova.md

The version linked previously would spam connections to "socket.io": "^2.2.0" on the back-end

Fix Socket.IO CDN

---

source/get-started/chat.md

Since npm 5 it's no longer needed:
https://stackoverflow.com/questions/19578796/what-is-the-save-option-for-npm-install

Remove --save option in npm commands

---

source/docs/index.md

Correct the spelling of packet in `What Socket.IO is not` section of index.md file

Update the index.md file with the correct spelling for packet

---

source/docs/emit-cheatsheet.md

Event names are used by library in client-api and should not be used by application.
Obsoletes PR:  abc order #138

add more backlist event names

---

source/docs/rooms-and-namespaces.md

making it clear that each socket joins  by default a room which is identified by "its own id". Earlier it said "this id" which may imply that all sockets connect to "this id".

updated documentation for default room

---

source/get-started/chat.md

Referencing issue #112. Only found one instance of "setup" where the correct use was "set up".

docs: Fixed grammar typo. Closes #112

---

source/docs/faq.md

I noticed your FAQ site links to `SIOSocket`, which links back to your own `socket.io-client-swift`. So here's the shortcut 😉

Update Outdated Link to iOS Client

---

source/docs/index.md

Change link for namespaces to redirect you to the namespace document. The original link was redirecting to the rooms document.

docs: redirect link to correct page.

---

source/docs/v3/rooms.md

Made a little fix on line 39 from `an union` to `a union`

changed word from an to a as a result of the the word `union` after it

---

source/docs/v3/index.md

Error `socket.onopen is not a function`
function should be assigned to socket.onopen and socket.onmessage

index.md WebSocket example fix

---

source/docs/v3/behind-a-reverse-proxy.md

I've searched the internet for hours trying to use socket.io through Caddy a couple months ago before I decided to ask in their forum.
[The solution they provided](https://caddy.community/t/i-cant-get-socket-io-proxy-to-work-on-v2/8703/2) works flawlessly and I'm sure it's beneficial to have that information directly on the socket.io website.

Add Caddy reverse proxy configuration example

---

source/docs/v4/client-socket-instance.md

Based on findings in /node_modules/socket.io-client/build/manager.js:338 (screenshot below)
Also get a type error when using 'reconnection_attempt'

Fix `on('reconnect_attempt')` event name

---

source/get-started/chat.md

In vscode, using this, will cause the intellisense to be lost.
```
const io = require("socket.io")(server);
``` 
Using the server object will make the intellisense come back
```
const { Server } = require("socket.io");
const io = new Server(server);
```

Using Server object from socket.io

---

source/docs/v4/emitting-events.md

Another options could be to change "are" to "is".

Noun should be plural for use with "are".

---

source/docs/v4/client-initialization.md

A Socket instance is the interface which is used to send events to — and receive events from — the server. It belongs to a given [namespace](/docs/v4/namespaces/).

Typo sends -> send

---

blog/2020-10-03-monthly-update.md
blog/2020-11-23-monthly-update.md
docs/categories/03-Client/client-installation.md
docs/categories/06-Advanced/custom-parser.md
docs/categories/07-Migrations/migrating-from-2-to-3.md
versioned_docs/version-3.x/categories/03-Client/client-installation.md
versioned_docs/version-3.x/categories/05-Advanced/custom-parser.md
versioned_docs/version-3.x/categories/06-Migrations/migrating-from-2-to-3.md

The links to the `socket.io-msgpack-parser` currently all use the old `https://github.com/darrachequesne/socket.io-msgpack-parser` URL, which now redirects to `https://github.com/socketio/socket.io-msgpack-parser`. This PR updates all references to the former to the latter.
When I was reading the custom parsers doc, when I first saw the link, my first thought was it was a "officially recognized third-party parser" as opposed to something that's first-party which I found on the clickthrough.

Update links to msgpack-parser to socket.io org

---

docusaurus.config.js

Prior this PR, there was no way to tell if we were reading a new version of the page apart from reading it entirely.
Now we'll get something like this at the bottom:

docs: add flag to show the last updated time

---

versioned_docs/version-3.x/categories/02-Server/behind-a-reverse-proxy.md

- The `handle_path` directive can be used to replace `handle` + `uri strip_prefix`: https://caddyserver.com/docs/caddyfile/directives/handle_path
- Setting those headers for `reverse_proxy` is unnecessary, Caddy already sets the appropriate headers automatically: https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#defaults

Simplify Caddyfile config

---

docs/categories/06-Advanced/admin-ui.md

Looks like that the module name is `bcryptjs`:
```js
> require("bcrypt").hashSync("changeit", 10)
Uncaught Error: Cannot find module 'bcrypt'
Require stack:
- <repl>
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
at Function.Module._load (node:internal/modules/cjs/loader:804:27)
at Module.require (node:internal/modules/cjs/loader:1028:19)
at require (node:internal/modules/cjs/helpers:102:18) {
code: 'MODULE_NOT_FOUND',
requireStack: [ '<repl>' ]
}
> require("bcryptjs").hashSync("changeit", 10)
'$2a$10$t9LpTAKdKJvGsVXqNsHF5eOKkAVsGvZsDR0r2aCdNXRy1n007QM7q'
>
```

Require `bcryptjs` instead of `bcrypt`

---

docs/categories/02-Server/behind-a-reverse-proxy.md

Because https://github.com/socketio/socket.io/discussions/4379 is one of the top results when searching for "socket.io caddy", I think the documentation should reflect the most common case where only a reverse proxy is needed in addition to the more specific case where the path is changed, while still keeping the custom path linked for anyone who needs it.

Further simplify caddyfile config

---

src/pages/get-started/chat.md

I genuinely don't see a reason (other than transphobic ones) to use `he/she` instead of `they`, hence why I'm making this PR

Use `they` instead of `he/she` in the `chat.md` file

---

docs/categories/04-Events/listening-to-events.md

The status 'KO' wasn't clear and relevant (at least to me), therefore I replaced it with a more relevant error message 'Bad Request'

 docs: fix error message

---

docs/categories/02-Server/server-initialization.md

The uWebSockets.js docs say to initialize the server by just calling `App()` rather than attempting to use the constructor `new App()` as portrayed in the example on the SocketIO docs, which doesn't work. 
(In Typescript, you get an error: `Only a void function can be called with the 'new' keyword.`)

docs: µWebSockets.js example initializes the server incorrectly

---

docs/categories/04-Events/rooms.md

Hi! Just noticed that there was an extra quotation mark character before `sids` in the docs

Fix: remove extra character in `rooms.md`

---

docs/categories/01-Documentation/troubleshooting.md

I faced the problem with **socket.io** and it's documentation didn't helped. So I spent some time to find the answer that my problem was a conflict between **express-status-monitor** and **socket.io** because status monitor also runs **socket.io** instance:
From their [github](https://github.com/RafalWilinski/express-status-monitor):
`If you're using socket.io in your project, this module could break your project because this module by default will spawn its own socket.io instance. To mitigate that, fill websocket parameter with your main socket.io instance as well as port parameter.`
So I think it will be helpful to add this case in the troubleshooting section.
I put a link on their GitHub repo where people can find a solution instead of writing the solution in docs just in case they …

Update troubleshooting section with express-status-monitor conflict case

---

docs/categories/02-Server/using-multiple-nodes.md

i wanted to save my solution for a sticky session(ip based) with the ingress controller in the kubernetes setup
promotion for another report
please also have an eye on my other idea, which should improve the typescript support
https://github.com/socketio/socket.io/issues/4808

Add sticky session documentation for nginx ingress ip based

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/categories/02-Server/server-socket-instance.md

I think it might should be "中间件" rather than "中间价", maybe @HereIsYui  chould help double check~

docs(zh): fix wrong word

---

docs/categories/02-Server/server-initialization.md

fastify.listen(MY_PORT) is deprecated since version 4.0.x. New way is to do is fastify.listen({ port: MY_PORT }).

Fix fastify's deprecated server.listen()

---

src/pages/how-to/use-with-react.md

This pull request corrects the directory structure presented in the example and amends the code to include the required import in the App.js illustration. I request the repository maintainers to review and merge it. Thanks.

docs: fix import in src/pages/how-to/use-with-react.md

---

docs/server-api.md

Wrong "socket" variable name reference when checking active connections; it should be "sockets".

Fix server-api.md sockets typo

---

docs/categories/04-Events/broadcasting-events.md

Small fix, but spotted redis adapter and adapters link were misplaced.

Fix misplaced adapters links in broadcasting events docs

---

docs/categories/02-Server/using-multiple-nodes.md
i18n/fr/docusaurus-plugin-content-docs/current/categories/02-Server/using-multiple-nodes.md
i18n/pt-br/docusaurus-plugin-content-docs/current/categories/02-Server/using-multiple-nodes.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/categories/02-Server/middlewares.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/categories/02-Server/using-multiple-nodes.md
src/pages/demos/chat.md
src/pages/demos/whiteboard.md

I found that the examples' links point to the 'master' branch. Instead, they should target the 'main' branch.

Fixed links to examples to point to 'main' branch instead of 'master'

---

blog/2014-05-28-1.0.0.md

The previous links do not lead to the appropriate sections within the document.  I updated the links to quickly jump the reader to the section to read without scrolling to the section.

Update broken link in the [Introducing Socket.IO 1.0] blog section

---

docs/categories/02-Server/server-installation.md
docs/categories/03-Client/client-installation.md
docs/tutorial/10-server-delivery.md
docs/tutorial/12-scaling-horizontally.md
i18n/fr/docusaurus-plugin-content-docs/current/categories/02-Server/server-installation.md
i18n/fr/docusaurus-plugin-content-docs/current/categories/03-Client/client-installation.md
i18n/fr/docusaurus-plugin-content-docs/current/tutorial/10-server-delivery.md
i18n/fr/docusaurus-plugin-content-docs/current/tutorial/12-scaling-horizontally.md
i18n/pt-br/docusaurus-plugin-content-docs/current/categories/02-Server/server-installation.md
i18n/pt-br/docusaurus-plugin-content-docs/current/categories/03-Client/client-installation.md
i18n/pt-br/docusaurus-plugin-content-docs/current/tutorial/10-server-delivery.md
i18n/pt-br/docusaurus-plugin-content-docs/current/tutorial/12-scaling-horizontally.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/categories/02-Server/server-installation.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/categories/03-Client/client-installation.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/tutorial/10-server-delivery.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/tutorial/12-scaling-horizontally.md

Adds bun as an option alongside npm/yarn/pnpm as a way to install socket.io on the server.
Here's a screenshot:

docs: add bun install as a server install option

---

docs/categories/06-Advanced/performance-tuning.md

This PR fixes issue #485 by removing dead links from the [Performance tuning](https://socket.io/docs/v4/performance-tuning/#at-the-os-level) documentation page.
For the second dead link, we can replace it with [this alternative](https://devops-insider.mygraphql.com/zh-cn/latest/network/tcp/ephemeral-port/ephemeral-port-exhaustion-and-how-to-avoid-it.html) or [this alternative](https://blog.cloudflare.com/how-to-stop-running-out-of-ephemeral-ports-and-start-to-love-long-lived-connections/) if needed.
Please do let me know, I will add this above link if required. Thanks!

docs: remove dead links from performance tuning page

---

docs/categories/01-Documentation/index.md

Fixes a small grammar issue in the docs:  
"detail" -> "details" in the `What Socket.IO is` section

fix(docs): make "detail" plural in What Socket.IO is section
