public/docs/rooms-and-namespaces/index.html
Fixed typo in Rooms and Namespaces section.
=> Fixed typo

source/docs/logging-and-debugging.md
This is the first time i'm using this DEBUG=* stuff, so fleshing it out a bit.
=> Expanded the section about filtering on scopes

source/docs/server-api.md
Fixed hyperlinks to match the correct `id` attribute in subtitle `<h2 id="...">` of the main site
=> Fixed id links

source/docs/client-api.md
Added 3rd possible reason for `disconnect` event to be triggered
=> Third reason for disconnect event

source/get-started/chat.md
node.js now uses createServer function in http module to create a server instead of Server
=> use createServer instead of Server

source/docs/rooms-and-namespaces.md
I am proposing to replace `var` with `const` (ES6-Syntax)
=> Replace var with const

source/docs/server-api.md
Removed unused server-creating line.
Was this intended?
=> Fixed wrong example

source/get-started/chat.md
Added one missing word in one of the early code blocks; and removed an extra 's' later in the tutorial.
=> Corrected two errors

themes/socket.io/source/js/home.js
=> Change user name by user id

source/get-started/chat.md
Added small clarifications about reloading, and removed the confusing parameter { for: 'everyone' } which looked like it's a keyword needed by the emit function.
=> Added some small clarifications for newbies

source/docs/server-api.md
I couldn't make it work as per current documentation. I suppose example has mistakes, I replaced it with how it worked for me.
=> Dynamic namespace documentation misleading

source/get-started/chat.md
Fix grammar, reword some phrases, update jQuery, convert some functions to ES6 syntax
=> General fixes of chat.md

source/docs/rooms.md
=> doc - spelling error fix

source/index.ejs
Update socket.io version number in the home page headline
=> docs: update socket.io version number

source/_posts/20201105-socket-io-3.md
Coming from this issue https://github.com/socketio/socket.io/issues/3695
=> Fix `updateitem` vs `update item` typo.

.gitignore, source/index.ejs, themes/socket.io/source/css/_partial/normalize.styl, themes/socket.io/source/css/home.styl
Not a big deal but fixed some mistakes. Love socket.io...
=> Fix css mistakes, Add .idea to .gitignore

source/get-started/index.md
Improve "Write a chat description" description by making the "here" word clickable for great user experience and friendliness.
=> docs(examples): Improve "Hello World" description

source/get-started/private-messaging-part-1.md
=> minor typo

source/get-started/private-messaging-part-2.md
Description says that the file is stored in the src dir but it's actually in the server dir
=> Fixed typo in Get started Part II

source/get-started/index.md
Update document link to v4 from v3
```
introducing [middlewares](/docs/v3/middlewares/) and [rooms](/docs/v3/rooms/) features.
```
↓
```
introducing [middlewares](/docs/v4/middlewares/) and [rooms](/docs/v4/rooms/) features.
```
=> get-started/index.md, change link to v4 from v3

source/get-started/chat.md
Changed 'http.listen(...' to 'server.listen(...'
=> Update chat.md to fix code typo. 

source/docs/v4/server-socket-instance.md
I'm super new to Socket.IO, but I was just trying this out and it seems, in the code sample, the connection will hang if the `try` block is successful and `next()` is not called.
=> Make sure middleware does not hang

docs/categories/02-Server/server-initialization.md
Wrong import express caught on 'Server Initialization' documentation page
=> Express example wrong import

docs/categories/01-Documentation/how-it-works.md, docs/categories/01-Documentation/index.md, docs/categories/01-Documentation/troubleshooting.md
Found these potential typos on the docs landing page.
=> Fixes potential typos

src/css/custom.css
Smooth scrolling doesn't work with docusaurus beta 2.0.0-15
resolves #333
=> Smooth scrolling doesn't work with docusarus beta 2.0.0-15

docs/categories/04-Events/emit-cheatsheet.md
A small change, but took me a minute to grasp the existing "basic emit" comment.
=> Update emit-cheatsheet.md comments

i18n/zh-CN/docusaurus-plugin-content-docs/current/categories/01-Documentation/connection-state-recovery.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/categories/01-Documentation/delivery-guarantees.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/categories/01-Documentation/how-it-works.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/categories/01-Documentation/index.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/categories/01-Documentation/logging-and-debugging.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/categories/01-Documentation/memory-usage.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/categories/01-Documentation/troubleshooting.md
@darrachequesne Please review~
=> Complete chinese translation under Documentation/Documentation section and fix some existing typos

docusaurus.config.js
An announcement bar to inform site visitors of paid user research opportunity.
=> Added announcement bar for user research

docs/categories/02-Server/server-installation.md
(added links to new release from 4.6.1 through to 4.7.1
=> Update server-installation.md 

docs/categories/01-Documentation/connection-state-recovery.md
The introduction was sloppy and was in passive tense. I updated it to active so the user knows who is doing what and to whom.
=> Update connection-state-recovery.md (mostly the introduction)

blog/2023-08-23-socketio-on-azure.md, blog/authors.yml, docusaurus.config.js
After conducting user study and gaining a better understanding of Socket.IO users' experience, we introduce support of Socket.IO on Azure. 
Adding a blog and banner to share this news with the Socket.IO user community.
=> Added a blog and banner to show support of Socket.IO on Azure

docs/categories/01-Documentation/testing.md
Adding integration test with vitest and TypeScript
=> Testing docs

docs/categories/02-Server/server-socket-instance.md, i18n/fr/docusaurus-plugin-content-docs/current/categories/02-Server/server-socket-instance.md, i18n/pt-br/docusaurus-plugin-content-docs/current/categories/02-Server/server-socket-instance.md, versioned_docs/version-3.x/categories/02-Server/server-socket-instance.md
Fixed multiple occurrences of the same typo.
=> docs: fix typo

docs/categories/05-Adapters/adapter-redis-streams.md
This pull request updates the Redis client configuration for improved consistency and readability.
Changes Made:
- Updated the Redis client configuration from using the `host` and `port` properties to a single `url` property, following best practices for Redis client configuration.
Before:
```javascript
const redisClient = createClient({ host: "localhost", port: 6379 });
```
After:
```javascript
const redisClient = createClient({ url: "redis://localhost:6379" });
```
This change simplifies the configuration and makes it easier to manage Redis connections.
Please review and merge this pull request at your earliest convenience.
Thank you.
=> #404: [docs] adapter-redis-streams client

docs/categories/06-Advanced/custom-parser.md
This type 2 (EVENT) event check is correct
https://github.com/advisories/GHSA-cqmj-92xf-r6r9
=> Edit docs custom parser

docs/categories/02-Server/server-initialization.md
This pull request adds an example for the server initialization with [Hono](https://hono.dev).
=> docs: Add server initialization with Hono

docs/categories/04-Events/listening-to-events.md
As zod is currently the most popular validation library, I placed it on the top.
=> Added zod to validation libaries

src/pages/how-to/use-with-nuxt.md
https://github.com/socketio/socket.io/issues/5208
=> docs: fix error in unjs/crossws > 0.3

i18n/zh-CN/docusaurus-theme-classic/footer.json
Change the copyright year from 2022 to 2025 in the Chinese footer configuration.
=> Update copyright year in Chinese footer.json
